schema_version: 1

context:
  python_min: "3.10"
  version: 1.0.0.dev3

package:
  name: prexsyn-engine
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/prexsyn-engine/prexsyn_engine-${{ version }}.tar.gz
  sha256: 9265fe9f1a9e2c0e2e2b5ecfd0eb0ddee521d969f9b42b37b459427b760d8032

build:
  skip:
    - not linux
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - python ${{ python_min }}.*
    - scikit-build-core
    - cmake
    - ninja
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - prexsyn_engine
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/prexsyn-engine/
  summary: 'C++ backend library for PrexSyn with Python bindings'
  documentation: https://prexsyn.readthedocs.io/
  repository: https://github.com/luost26/prexsyn-engine

extra:
  recipe-maintainers:
    - luost26
